In [1]:
from datasets import load_dataset
from sklearn.model_selection import train_test_split
import pandas as pd

# Load dataset
ds = load_dataset("tinixai/vietnam-real-estates")

# Convert sang pandas
df = ds["train"].to_pandas()

# Chỉ lấy dữ liệu nhà
df_house = df[df["property_type_name"] == "Nhà"]

# Kiểm tra
print(df_house.shape)

# Xem vài dòng
df_house.head(3)

/Users/Huy/VSCode/KHDL/projectCK/venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

(1575536, 19)

,name,description,property_type_name,province_name,district_name,ward_name,street_name,project_name,price,area,floor_count,frontage_width,house_depth,road_width,bedroom_count,bathroom_count,house_direction,balcony_direction,published_at
0,"Bán nhanh nhà 6 tầng thang máy, ngoạ long cầu ...","- Vị trí siêu đẹp ô tô đỗ cổng, khu vực đang p...",Nhà,Hà Nội,Bắc Từ Liêm,Phúc Diễn,Ngọa Long,NaN,7.450000e+09,37.0,NaN,NaN,NaN,NaN,4.0,5.0,NaN,NaN,2025-06-01T05:12:56.941000
1,Bán gấp nhà mặt tiền 4 tầng khu phân lô Tạ Qua...,Nhà 4 tầng mặt tiền KDC Tạ Quang Bửu P5 Q8. - ...,Nhà,Hồ Chí Minh,8,5,Tạ Quang Bửu,NaN,9.100000e+09,48.0,4.0,4.0,NaN,NaN,3.0,3.0,NaN,NaN,2025-06-06T04:37:25.903000
4,"MTKD p.Tân Thành, Tân Phú, dt 4x15m sẵn hợp đồ...","MTKD p.Tân Thành, Tân Phú, dt 4x15m sẵn hợp đồ...",Nhà,Hồ Chí Minh,Tân Phú,Tân Thành,Nguyễn Hậu,NaN,9.000000e+09,60.0,NaN,NaN,NaN,NaN,2.0,3.0,NaN,NaN,2025-06-06T04:06:17.378000

In [2]:
df_house = df_house.reset_index(drop=True)
df_house["property_type_name"].unique()

<ArrowStringArray>
['Nhà']
Length: 1, dtype: str

In [3]:
# df_house = ds["train"].to_pandas()

In [4]:
df_house.info()

<class 'pandas.DataFrame'>
RangeIndex: 1575536 entries, 0 to 1575535
Data columns (total 19 columns):
 #   Column              Non-Null Count    Dtype
---  ------              --------------    -----
 0   name                1575536 non-null  str
 1   description         1575536 non-null  str
 2   property_type_name  1575536 non-null  str
 3   province_name       1575536 non-null  str
 4   district_name       1557448 non-null  str
 5   ward_name           1406068 non-null  str
 6   street_name         1212702 non-null  str
 7   project_name        28446 non-null    str
 8   price               1506814 non-null  float64
 9   area                1575536 non-null  float64
 10  floor_count         649819 non-null   float64
 11  frontage_width      960953 non-null   float64
 12  house_depth         26139 non-null    float64
 13  road_width          338132 non-null   float64
 14  bedroom_count       1026097 non-null  float64
 15  bathroom_count      939093 non-null   float64
 16  house_direction     293969 non-null   str
 17  balcony_direction   155179 non-null   str
 18  published_at        1575536 non-null  str
dtypes: float64(8), str(11)
memory usage: 1.4 GB

In [5]:
missing_values = df_house.isnull().sum()

missing_percentage = (missing_values / len(df_house)) * 100

missing_df = pd.DataFrame({
    "Missing Values": missing_values,
    "Missing (%)": missing_percentage
})

missing_df.sort_values(by="Missing Values", ascending=False)

                    Missing Values  Missing (%)
house_depth                1549397    98.340946
project_name               1547090    98.194519
balcony_direction          1420357    90.150717
house_direction            1281567    81.341651
road_width                 1237404    78.538605
floor_count                 925717    58.755687
bathroom_count              636443    40.395332
frontage_width              614583    39.007868
bedroom_count               549439    34.873148
street_name                 362834    23.029242
ward_name                   169468    10.756212
price                        68722     4.361817
district_name                18088     1.148054
name                             0     0.000000
area                             0     0.000000
description                      0     0.000000
province_name                    0     0.000000
property_type_name               0     0.000000
published_at                     0     0.000000

In [6]:
print("Thống kê mô tả cho các cột số:")
df.describe().T

Thống kê mô tả cho các cột số:

,count,mean,std,min,25%,50%,75%,max
price,3282250.0,2.958440e+10,1.486320e+13,0.00,4.000000e+09,7.300000e+09,1.400000e+10,2.659719e+16
area,3500740.0,5.050264e+02,9.726008e+04,1.00,5.600000e+01,8.000000e+01,1.200000e+02,8.200000e+07
floor_count,808762.0,3.853717e+00,1.753971e+00,1.00,3.000000e+00,4.000000e+00,5.000000e+00,2.550000e+02
frontage_width,1774320.0,2.731670e+01,1.077600e+04,0.38,4.200000e+00,5.000000e+00,7.500000e+00,9.080000e+06
house_depth,68456.0,2.398837e+01,9.498039e+01,1.00,1.350000e+01,1.872000e+01,2.460000e+01,1.538000e+04
road_width,669871.0,9.571250e+00,1.329914e+02,0.50,4.000000e+00,6.000000e+00,1.000000e+01,1.030000e+05
bedroom_count,1900383.0,3.373194e+00,2.713995e+00,1.00,2.000000e+00,3.000000e+00,4.000000e+00,2.000000e+02
bathroom_count,1779770.0,3.130349e+00,2.670448e+00,1.00,2.000000e+00,2.000000e+00,4.000000e+00,2.550000e+02

In [7]:

# df_sample = df_house.sample(
#     n=300000,
#     random_state=42
# )
# df_sample = df.sample(
#     n=300000,
#     random_state=42
# )

train_df, test_df = train_test_split(
    df_house,
    test_size=0.2,
    random_state=42
)

In [8]:
train_df.to_csv(
    "../data/raw/raw_data_train.csv",
    index=False
)

test_df.to_csv(
    "../data/raw/raw_data_test.csv",
    index=False
)